variables:
  BUILD_IMAGE: $CI_REGISTRY_IMAGE/build:$CI_COMMIT_REF_SLUG
  NIGHTLY_IMAGE: $CI_REGISTRY_IMAGE/nightly:$CI_COMMIT_REF_SLUG

stages:
  - build
  - clippy
  - test

docker-build-master:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$BUILD_IMAGE" .
    - docker push "$BUILD_IMAGE"
  only:
    - master

docker-build-nightly:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$NIGHTLY_IMAGE" -f Dockerfile.nightly .
    - docker push "$NIGHTLY_IMAGE"
  only:
    - master

clippy:
  stage: clippy
  image: $BUILD_IMAGE
  before_script:
    - rm -fr ~/.cargo/registry && mkdir -p /cache/registry && ln -s /cache/registry ~/.cargo/registry
    - rm -fr ~/.cargo/git && mkdir -p /cache/git && ln -s /cache/git ~/.cargo/git
    - rm -fr target && mkdir -p /cache/$CI_COMMIT_REF_SLUG/target && ln -s /cache/$CI_COMMIT_REF_SLUG/target target
    - source ~/.cargo/env
    - rustc --version
  script:
    - RUSTFLAGS="-D warnings" CARGO_INCREMENTAL=1 RUST_BACKTRACE=1 cargo clippy

test:
  stage: test
  image: $BUILD_IMAGE
  services:
    - name: mongo:latest
      alias: standard
      command:
        [
          "mongod",
          "--storageEngine",
          "ephemeralForTest",
          "--dbpath",
          "/data/db",
        ]
    - name: mongo:latest
      alias: repl
      command:
        [
          "mongod",
          "--replSet",
          "rs0",
          "--enableMajorityReadConcern",
          "--storageEngine",
          "ephemeralForTest",
          "--dbpath",
          "/data/db",
        ]
  before_script:
    - rm -fr ~/.cargo/registry && mkdir -p /cache/registry && ln -s /cache/registry ~/.cargo/registry
    - rm -fr ~/.cargo/git && mkdir -p /cache/git && ln -s /cache/git ~/.cargo/git
    - rm -fr target && mkdir -p /cache/$CI_COMMIT_REF_SLUG/target && ln -s /cache/$CI_COMMIT_REF_SLUG/target target
    - source ~/.cargo/env
    - rustc --version
  script:
    - RUSTFLAGS="-D warnings" CARGO_INCREMENTAL=1 RUST_BACKTRACE=1 cargo test -- --nocapture

test_nightly:
  stage: test
  image: $NIGHTLY_IMAGE
  services:
    - name: mongo:latest
      alias: standard
      command:
        [
          "mongod",
          "--storageEngine",
          "ephemeralForTest",
          "--dbpath",
          "/data/db",
        ]
    - name: mongo:latest
      alias: repl
      command:
        [
          "mongod",
          "--replSet",
          "rs0",
          "--enableMajorityReadConcern",
          "--storageEngine",
          "ephemeralForTest",
          "--dbpath",
          "/data/db",
        ]
  before_script:
    - rm -fr ~/.cargo/registry && mkdir -p /cache/registry && ln -s /cache/registry ~/.cargo/registry
    - rm -fr ~/.cargo/git && mkdir -p /cache/git && ln -s /cache/git ~/.cargo/git
    - rm -fr target && mkdir -p /cache/$CI_COMMIT_REF_SLUG/target && ln -s /cache/$CI_COMMIT_REF_SLUG/target target
    - source ~/.cargo/env
    - rustc --version
  script:
    - RUSTFLAGS="-D warnings" CARGO_INCREMENTAL=1 RUST_BACKTRACE=1 cargo test -- --nocapture
