variables:
  BUILD_IMAGE: $CI_REGISTRY_IMAGE/build
  NIGHTLY_IMAGE: $CI_REGISTRY_IMAGE/nightly

stages:
  - build
  - test

services:
  - name: mongo:latest
    alias: standard
    command:
      ["mongod", "--storageengine", "ephemeralfortest", "--dbpath", "/data/db"]
  - name: mongo:latest
    alias: repl
    command:
      [
        "mongod",
        "--replset",
        "rs0",
        "--enablemajorityreadconcern",
        "--storageengine",
        "ephemeralfortest",
        "--dbpath",
        "/data/db",
      ]

docker-build-master:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker pull $BUILD_IMAGE:latest || true
    - docker build --cache-from $BUILD_IMAGE:latest --tag $BUILD_IMAGE:$CI_COMMIT_SHA --tag $BUILD_IMAGE:latest .
    - docker push $BUILD_IMAGE:$CI_COMMIT_SHA
    - docker push $BUILD_IMAGE:latest
  only:
    - master

docker-build-nightly:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker pull $NIGHTLY_IMAGE:latest || true
    - docker build --cache-from $NIGHTLY_IMAGE:latest --tag $NIGHTLY_IMAGE:$CI_COMMIT_SHA --tag $NIGHTLY_IMAGE:latest .
    - docker push $NIGHTLY_IMAGE:$CI_COMMIT_SHA
    - docker push $NIGHTLY_IMAGE:latest
  only:
    - master

init-db-for-test:
  stage: build
  image: mongo:latest
  script:
    - mongo --host repl --eval 'rs.initiate();'

clippy:
  image: $BUILD_IMAGE:latest
  stage: test
  script:
    - cargo clippy
  only:
    - master

test:
  image: $BUILD_IMAGE:latest
  stage: test
  script:
    - cargo test --all
  only:
    - master

test_nightly:
  image: $NIGHTLY_IMAGE:latest
  stage: test
  script:
    - cargo test --all
  only:
    - master
