variables:
  BUILD_IMAGE: $CI_REGISTRY_IMAGE/build
  NIGHTLY_IMAGE: $CI_REGISTRY_IMAGE/nightly

stages:
  - build
  - test

docker-build-master:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker pull $BUILD_IMAGE:latest || true
    - docker build --cache-from $BUILD_IMAGE:latest --tag $BUILD_IMAGE:$CI_COMMIT_SHA --tag $BUILD_IMAGE:latest .
    - docker push $BUILD_IMAGE:$CI_COMMIT_SHA
    - docker push $BUILD_IMAGE:latest
  only:
    - master

docker-build-nightly:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker pull $NIGHTLY_IMAGE:latest || true
    - docker build --cache-from $NIGHTLY_IMAGE:latest --tag $NIGHTLY_IMAGE:$CI_COMMIT_SHA --tag $NIGHTLY_IMAGE:latest .
    - docker push $NIGHTLY_IMAGE:$CI_COMMIT_SHA
    - docker push $NIGHTLY_IMAGE:latest
  only:
    - master

init-db-for-test:
  stage: build
  image: mongo:latest
  script:
    - mongo --host repl --eval 'rs.initiate();'

clippy:
  # Official docker image.
  image: docker:latest
  stage: test
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker run $BUILD_IMAGE:latest cargo clippy
  only:
    - master

test:
  # Official docker image.
  image: docker:latest
  stage: test
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker run -d --rm --name standard mongo:latest
    - docker run -d --rm --name replSet mongo:latest mongod --replSet rs0 --enableMajorityReadConcern
    - docker run --rm --link replSet mongo:latest mongo --host replSet --eval 'rs.initiate();'
  script:
    - docker run --rm --link replSet --link standard $BUILD_IMAGE:latest cargo test --all
    - docker stop standard
    - docker stop replSet
  only:
    - master

test_nightly:
  # Official docker image.
  image: docker:latest
  stage: test
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker run -d --rm --name standard mongo:latest
    - docker run -d --rm --name replSet mongo:latest mongod --replSet rs0 --enableMajorityReadConcern
    - docker run --rm --link replSet mongo:latest mongo --host replSet --eval 'rs.initiate();'
  script:
    - docker run --rm --link replSet --link standard $NIGHTLY_IMAGE:latest cargo test --all
    - docker stop standard
    - docker stop replSet
  only:
    - master
