image: rust:latest

services:
- name: mongo:latest

before_script:
  - apt update && apt install -y cmake libssl-dev clang > apt-build.log 2>&1

stages:
  - build

rust-latest:
  when: manual
  stage: build
  image: rust:latest
  variables:
    MONGODB_URI: "mongodb://mongo/"
  script:
    - cargo build > build.log 2>&1
    - cargo test -q --doc

rust-nightly:
  when: manual
  stage: build
  image: rustlang/rust:nightly
  variables:
    MONGODB_URI: "mongodb://mongo/"
  script:
    - cargo build > build.log 2>&1
    - cargo test -q --doc
  allow_failure: true
