image: rust:latest

services:
- name: mongo:latest

before_script:
  - apt update && apt install -y cmake libssl-dev clang

stages:
  - build

rust-latest:
  when: manual
  stage: build
  image: rust:latest
  variables:
    MONGODB_URI: "mongodb://mongo/"
  script:
    - cargo build
    - cargo test --verbose

rust-nightly:
  when: manual
  stage: build
  image: rustlang/rust:nightly
  variables:
    MONGODB_URI: "mongodb://mongo/"
  script:
    - cargo build
    - cargo test --verbose
  allow_failure: true
