variables:
  BUILD_IMAGE: $CI_REGISTRY_IMAGE/build:$CI_COMMIT_REF_SLUG
  NIGHTLY_IMAGE: $CI_REGISTRY_IMAGE/nightly:$CI_COMMIT_REF_SLUG
  DEPLOY_IMAGE: $CI_REGISTRY_IMAGE:$CI_BUILD_TAG
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - build
  - clippy
  - test

init_repl:
  stage: .pre
  image: mongo:latest
  script:
    - mongo --host repl --eval 'rs.initiate();'

create_build_image:
  stage: build
  image: docker:19.03.1-dind
  tags: [docker]
  before_script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build --pull -t $BUILD_IMAGE -f Dockerfile .
    - docker push $BUILD_IMAGE
    - echo "Pushed $BUILD_IMAGE"

create_nightly_image:
  stage: build
  image: docker:19.03.1-dind
  tags: [docker]
  services:
    - name: $CI_REGISTRY/group/project/docker:19.03.1-dind
      alias: docker
  before_script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build -q --pull -t $NIGHTLY_IMAGE -f Dockerfile.nightly .
    - docker push $NIGHTLY_IMAGE
    - echo "Pushed $NIGHTLY_IMAGE"

clippy:
  stage: clippy
  image: $BUILD_IMAGE
  before_script:
    - rm -fr ~/.cargo/registry && mkdir -p /cache/registry && ln -s /cache/registry ~/.cargo/registry
    - rm -fr ~/.cargo/git && mkdir -p /cache/git && ln -s /cache/git ~/.cargo/git
    - rm -fr target && mkdir -p /cache/$CI_COMMIT_REF_SLUG/target && ln -s /cache/$CI_COMMIT_REF_SLUG/target target
    - source ~/.cargo/env
    - rustc --version
  script:
    - RUSTFLAGS="-D warnings" CARGO_INCREMENTAL=1 RUST_BACKTRACE=1 cargo clippy

test:
  stage: test
  image: $BUILD_IMAGE
  services:
    - name: mongo:latest
      alias: standard
      command:
        [
          "mongod",
          "--storageEngine",
          "ephemeralForTest",
          "--dbpath",
          "/data/db",
        ]
    - name: mongo:latest
      alias: repl
      command:
        [
          "mongod",
          "--replSet",
          "rs0",
          "--enableMajorityReadConcern",
          "--storageEngine",
          "ephemeralForTest",
          "--dbpath",
          "/data/db",
        ]
  before_script:
    - rm -fr ~/.cargo/registry && mkdir -p /cache/registry && ln -s /cache/registry ~/.cargo/registry
    - rm -fr ~/.cargo/git && mkdir -p /cache/git && ln -s /cache/git ~/.cargo/git
    - rm -fr target && mkdir -p /cache/$CI_COMMIT_REF_SLUG/target && ln -s /cache/$CI_COMMIT_REF_SLUG/target target
    - source ~/.cargo/env
    - rustc --version
  script:
    - RUSTFLAGS="-D warnings" CARGO_INCREMENTAL=1 RUST_BACKTRACE=1 cargo test -- --nocapture

test_nightly:
  stage: test
  image: $NIGHTLY_IMAGE
  services:
    - name: mongo:latest
      alias: standard
      command:
        [
          "mongod",
          "--storageEngine",
          "ephemeralForTest",
          "--dbpath",
          "/data/db",
        ]
    - name: mongo:latest
      alias: repl
      command:
        [
          "mongod",
          "--replSet",
          "rs0",
          "--enableMajorityReadConcern",
          "--storageEngine",
          "ephemeralForTest",
          "--dbpath",
          "/data/db",
        ]
  before_script:
    - rm -fr ~/.cargo/registry && mkdir -p /cache/registry && ln -s /cache/registry ~/.cargo/registry
    - rm -fr ~/.cargo/git && mkdir -p /cache/git && ln -s /cache/git ~/.cargo/git
    - rm -fr target && mkdir -p /cache/$CI_COMMIT_REF_SLUG/target && ln -s /cache/$CI_COMMIT_REF_SLUG/target target
    - source ~/.cargo/env
    - rustc --version
  script:
    - RUSTFLAGS="-D warnings" CARGO_INCREMENTAL=1 RUST_BACKTRACE=1 cargo test -- --nocapture
