[package]
name = "mongo-leaf"
version = "0.1.0"
authors = ["Zac Kleinpeter <zac@kleinpeter.org>"]
edition = "2018"
build = "build.rs"

[dependencies]
libc        = "0.2"
openssl-sys = { version = "0.9", features = ["vendored"] }
bson = "0.14.0"
rand = "0.7.2"
failure = "0.1.6"
failure_derive = "0.1.6"

#[badges]
#gitlab = { repository = "...", branch = "master" }

[build-dependencies]
bindgen = "0.51.1"
cmake = "0.1"
pkg-config = "0.3"
vcpkg = "0.2.6"
